"""databases_synchronization_all_01

Revision ID: 28610fc498ab
Revises: 73e2fea06565
Create Date: 2022-09-21 11:33:13.112105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28610fc498ab'
down_revision = '73e2fea06565'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
