"""33333

Revision ID: 31fdf8af244a
Revises: 5fb77ca8cd45
Create Date: 2022-09-22 19:58:39.287374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31fdf8af244a'
down_revision = '5fb77ca8cd45'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
