"""databases_synchronization_all_02

Revision ID: 5af160f8fae9
Revises: 28610fc498ab
Create Date: 2022-09-21 11:34:41.918273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5af160f8fae9'
down_revision = '28610fc498ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
