"""33333

Revision ID: 5fb77ca8cd45
Revises: 8017238ec8fe
Create Date: 2022-09-22 19:56:29.064544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fb77ca8cd45'
down_revision = '8017238ec8fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
