"""index_delete_users

Revision ID: 75e4fdd5ca41
Revises: ae1db276c44e
Create Date: 2022-09-22 19:14:51.458425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75e4fdd5ca41'
down_revision = 'ae1db276c44e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_items_brief_introduction', table_name='items')
    op.drop_index('ix_items_id', table_name='items')
    op.drop_index('ix_items_mail', table_name='items')
    op.create_index(op.f('ix_items_mail'), 'items', ['mail'], unique=True)
    op.add_column('users', sa.Column('name', sa.String(length=20), nullable=True))
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('ix_users_password', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_password', 'users', ['password'], unique=False)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.drop_column('users', 'name')
    op.drop_index(op.f('ix_items_mail'), table_name='items')
    op.create_index('ix_items_mail', 'items', ['mail'], unique=False)
    op.create_index('ix_items_id', 'items', ['id'], unique=False)
    op.create_index('ix_items_brief_introduction', 'items', ['brief_introduction'], unique=False)
    # ### end Alembic commands ###
