"""33333

Revision ID: 8017238ec8fe
Revises: b3ec4217c10d
Create Date: 2022-09-22 19:55:01.188589

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8017238ec8fe'
down_revision = 'b3ec4217c10d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'mail',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'mail',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=50),
               nullable=True)
    # ### end Alembic commands ###
