"""mobile_field_add

Revision ID: ae1db276c44e
Revises: 5af160f8fae9
Create Date: 2022-09-22 14:45:32.331103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae1db276c44e'
down_revision = '5af160f8fae9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mobile', sa.String(length=11), nullable=True))
    op.create_index(op.f('ix_users_mobile'), 'users', ['mobile'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_mobile'), table_name='users')
    op.drop_column('users', 'mobile')
    # ### end Alembic commands ###
