"""add_password_length

Revision ID: b3ec4217c10d
Revises: 75e4fdd5ca41
Create Date: 2022-09-22 19:52:26.300903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3ec4217c10d'
down_revision = '75e4fdd5ca41'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
