"""同步报告表

Revision ID: 4c6f4ec5bcbb
Revises: 9e98de80b692
Create Date: 2023-06-30 16:50:48.237839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c6f4ec5bcbb'
down_revision = '9e98de80b692'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=10), nullable=False),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('total_succeed', sa.Integer(), nullable=True),
    sa.Column('total_defeated', sa.Integer(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_id'), 'report', ['id'], unique=False)
    op.create_table('report_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('succeed_results', sa.String(length=500), nullable=True),
    sa.Column('defeated_results', sa.String(length=500), nullable=True),
    sa.Column('error_results', sa.String(length=500), nullable=True),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_record_id'), 'report_record', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_record_id'), table_name='report_record')
    op.drop_table('report_record')
    op.drop_index(op.f('ix_report_id'), table_name='report')
    op.drop_table('report')
    # ### end Alembic commands ###
