"""cases表字段增加长度

Revision ID: 79d457fe882e
Revises: 809d52799186
Create Date: 2023-06-16 13:47:51.302936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79d457fe882e'
down_revision = '809d52799186'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
