"""新增cases表

Revision ID: 809d52799186
Revises: 
Create Date: 2023-06-16 11:51:24.591919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '809d52799186'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.Column('body_type', sa.String(length=10), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=True),
    sa.Column('content', sa.String(length=500), nullable=True),
    sa.Column('files', sa.String(length=500), nullable=True),
    sa.Column('params', sa.String(length=500), nullable=True),
    sa.Column('headers', sa.String(length=500), nullable=True),
    sa.Column('cookies', sa.String(length=500), nullable=True),
    sa.Column('timeout', sa.FLOAT(), nullable=True),
    sa.Column('auth', sa.String(length=500), nullable=True),
    sa.Column('follow_redirects', sa.String(length=500), nullable=True),
    sa.Column('extensions', sa.String(length=500), nullable=True),
    sa.Column('expected_result', sa.String(length=500), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_id'), 'cases', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=50), nullable=True),
    sa.Column('mailbox', sa.String(length=100), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_cases_id'), table_name='cases')
    op.drop_table('cases')
    # ### end Alembic commands ###
