"""测试报告表增加字典

Revision ID: a9a79348ba27
Revises: be51dcb03572
Create Date: 2023-07-19 20:25:16.993673

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a9a79348ba27'
down_revision = 'be51dcb03572'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case', 'expected_result')
    op.add_column('report', sa.Column('success_rate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'success_rate')
    op.add_column('case', sa.Column('expected_result', mysql.JSON(), nullable=True))
    # ### end Alembic commands ###
