"""更新测试报告记录表

Revision ID: c3c838d2ea7e
Revises: 4b2a6cd3ad14
Create Date: 2023-07-20 16:25:22.021144

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c3c838d2ea7e'
down_revision = '4b2a6cd3ad14'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_record', sa.Column('response', sa.JSON(), nullable=True))
    op.drop_column('report_record', 'defeated_results')
    op.drop_column('report_record', 'error_results')
    op.drop_column('report_record', 'succeed_results')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_record', sa.Column('succeed_results', mysql.JSON(), nullable=True))
    op.add_column('report_record', sa.Column('error_results', mysql.TEXT(collation='utf8mb4_zh_0900_as_cs'), nullable=True))
    op.add_column('report_record', sa.Column('defeated_results', mysql.JSON(), nullable=True))
    op.drop_column('report_record', 'response')
    # ### end Alembic commands ###
