"""同步表结构

Revision ID: f7a0e582ab99
Revises: 
Create Date: 2023-07-07 16:44:49.506133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7a0e582ab99'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.Column('body_type', sa.String(length=10), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=True),
    sa.Column('content', sa.String(length=500), nullable=True),
    sa.Column('files', sa.String(length=500), nullable=True),
    sa.Column('params', sa.String(length=500), nullable=True),
    sa.Column('headers', sa.String(length=500), nullable=True),
    sa.Column('cookies', sa.String(length=500), nullable=True),
    sa.Column('timeout', sa.Float(), nullable=True),
    sa.Column('expected_result', sa.String(length=500), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('is_delete', sa.Integer(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_id'), 'case', ['id'], unique=False)
    op.create_table('plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('environment', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_delete', sa.Integer(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_id'), 'plan', ['id'], unique=False)
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=10), nullable=False),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('total_succeed', sa.Integer(), nullable=True),
    sa.Column('total_defeated', sa.Integer(), nullable=True),
    sa.Column('is_delete', sa.Integer(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_id'), 'report', ['id'], unique=False)
    op.create_table('report_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('succeed_results', sa.String(length=500), nullable=True),
    sa.Column('defeated_results', sa.String(length=500), nullable=True),
    sa.Column('error_results', sa.String(length=500), nullable=True),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_record_id'), 'report_record', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=500), nullable=True),
    sa.Column('is_delete', sa.Integer(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_report_record_id'), table_name='report_record')
    op.drop_table('report_record')
    op.drop_index(op.f('ix_report_id'), table_name='report')
    op.drop_table('report')
    op.drop_index(op.f('ix_plan_id'), table_name='plan')
    op.drop_table('plan')
    op.drop_index(op.f('ix_case_id'), table_name='case')
    op.drop_table('case')
    # ### end Alembic commands ###
