"""修改datas表中的数据类型,增加注释信息

Revision ID: 0c335de45572
Revises: 2c2949fcecfa
Create Date: 2022-09-29 09:05:11.867663

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0c335de45572'
down_revision = '2c2949fcecfa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('datas', 'title',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=20),
               comment='名称',
               existing_nullable=False)
    op.alter_column('datas', 'method',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=10),
               comment='请求方式',
               existing_nullable=False)
    op.alter_column('datas', 'url',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=200),
               comment='请求的URL',
               existing_nullable=False)
    op.alter_column('datas', 'headers',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=200),
               comment='请求的头部信息',
               existing_nullable=False)
    op.alter_column('datas', 'body_type',
               existing_type=mysql.INTEGER(display_width=11),
               comment='请求类型，区分json、form-data等',
               existing_nullable=False)
    op.alter_column('datas', 'params',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=50),
               comment='请求参数-params',
               existing_nullable=True)
    op.alter_column('datas', 'body',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=200),
               comment='请求参数-body体',
               existing_nullable=True)
    op.alter_column('datas', 'cookies',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=200),
               comment='cookies',
               existing_nullable=True)
    op.alter_column('datas', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否被删除',
               existing_nullable=True)
    op.alter_column('datas', 'created_time',
               existing_type=mysql.TIMESTAMP(),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('datas', 'updated_time',
               existing_type=mysql.TIMESTAMP(),
               comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('datas', 'updated_time',
               existing_type=mysql.TIMESTAMP(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
    op.alter_column('datas', 'created_time',
               existing_type=mysql.TIMESTAMP(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('datas', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否被删除',
               existing_nullable=True)
    op.alter_column('datas', 'cookies',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=200),
               comment=None,
               existing_comment='cookies',
               existing_nullable=True)
    op.alter_column('datas', 'body',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=200),
               comment=None,
               existing_comment='请求参数-body体',
               existing_nullable=True)
    op.alter_column('datas', 'params',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=50),
               comment=None,
               existing_comment='请求参数-params',
               existing_nullable=True)
    op.alter_column('datas', 'body_type',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='请求类型，区分json、form-data等',
               existing_nullable=False)
    op.alter_column('datas', 'headers',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=200),
               comment=None,
               existing_comment='请求的头部信息',
               existing_nullable=False)
    op.alter_column('datas', 'url',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=200),
               comment=None,
               existing_comment='请求的URL',
               existing_nullable=False)
    op.alter_column('datas', 'method',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=10),
               comment=None,
               existing_comment='请求方式',
               existing_nullable=False)
    op.alter_column('datas', 'title',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=20),
               comment=None,
               existing_comment='名称',
               existing_nullable=False)
    # ### end Alembic commands ###
