"""新增plan表，用于存储测试计划

Revision ID: 28356eac1890
Revises: aec8902e1e9c
Create Date: 2022-10-18 18:31:17.394640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28356eac1890'
down_revision = 'aec8902e1e9c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='计划名称'),
    sa.Column('principal', sa.String(length=50), nullable=False, comment='项目负责人名称'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否被删除'),
    sa.Column('created_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_time', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plan')
    # ### end Alembic commands ###
