"""增加report表...

Revision ID: 2c1ddb0e90cd
Revises: 344ac3759d35
Create Date: 2022-10-09 11:27:13.759532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c1ddb0e90cd'
down_revision = '344ac3759d35'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_datas', sa.TEXT(), nullable=False, comment='测试报告数据'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否被删除'),
    sa.Column('created_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_time', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    # ### end Alembic commands ###
