"""迁移数据信息

Revision ID: 31e4700df5e7
Revises: 471be68f6096
Create Date: 2022-10-31 17:34:12.913652

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '31e4700df5e7'
down_revision = '471be68f6096'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan', 'principal')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan', sa.Column('principal', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=False, comment='项目负责人名称'))
    # ### end Alembic commands ###
