"""增加report表，cases表中增加is_fail字段

Revision ID: 5582e6323409
Revises: dc2cc655245f
Create Date: 2022-10-09 11:22:02.182644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5582e6323409'
down_revision = 'dc2cc655245f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('is_fail', sa.Boolean(), nullable=True, comment='是否执行失败'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'is_fail')
    # ### end Alembic commands ###
