"""创建cases表

Revision ID: 785c21a31910
Revises: b87b7aba7d8d
Create Date: 2022-09-30 09:57:23.205517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '785c21a31910'
down_revision = 'b87b7aba7d8d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('datas', sa.TEXT(), nullable=False),
    sa.Column('actual', sa.TEXT(), nullable=True, comment='断言使用-接口的实际结果'),
    sa.Column('expect', sa.TEXT(), nullable=True, comment='断言使用-接口的预期结果'),
    sa.Column('comparison', sa.TEXT(), nullable=True, comment='断言比较符号'),
    sa.Column('is_success', sa.Boolean(), nullable=True, comment='是否执行成功'),
    sa.Column('is_error', sa.Boolean(), nullable=True, comment='是否错误'),
    sa.Column('exception', sa.TEXT(), nullable=True, comment='报错异常捕获'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否被删除'),
    sa.Column('created_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_time', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('datas', sa.Column('comparison', sa.TEXT(), nullable=True, comment='断言比较符号'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datas', 'comparison')
    op.drop_table('cases')
    # ### end Alembic commands ###
