"""删除cases表中的预期结果和实际结果字段

Revision ID: 8f1c525a7d90
Revises: 785c21a31910
Create Date: 2022-09-30 11:53:21.278005

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8f1c525a7d90'
down_revision = '785c21a31910'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cases', 'name',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=20),
               comment='用例名称',
               existing_nullable=False)
    op.alter_column('cases', 'datas',
               existing_type=mysql.TEXT(collation='utf8_bin'),
               comment='测试数据，请求方式、请求体、请求头、预期和实际结果',
               existing_nullable=False)
    op.drop_column('cases', 'actual')
    op.drop_column('cases', 'expect')
    op.drop_column('cases', 'comparison')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('comparison', mysql.TEXT(collation='utf8_bin'), nullable=True, comment='断言比较符号'))
    op.add_column('cases', sa.Column('expect', mysql.TEXT(collation='utf8_bin'), nullable=True, comment='断言使用-接口的预期结果'))
    op.add_column('cases', sa.Column('actual', mysql.TEXT(collation='utf8_bin'), nullable=True, comment='断言使用-接口的实际结果'))
    op.alter_column('cases', 'datas',
               existing_type=mysql.TEXT(collation='utf8_bin'),
               comment=None,
               existing_comment='测试数据，请求方式、请求体、请求头、预期和实际结果',
               existing_nullable=False)
    op.alter_column('cases', 'name',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=20),
               comment=None,
               existing_comment='用例名称',
               existing_nullable=False)
    # ### end Alembic commands ###
