"""datas表中增加实际结果和预期结果字段，用于断言使用

Revision ID: be84012a0895
Revises: 0c335de45572
Create Date: 2022-09-29 11:27:28.056329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be84012a0895'
down_revision = '0c335de45572'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datas', sa.Column('actual', sa.TEXT(), nullable=True, comment='断言使用-接口的实际结果'))
    op.add_column('datas', sa.Column('expect', sa.TEXT(), nullable=True, comment='断言使用-接口的预期结果'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datas', 'expect')
    op.drop_column('datas', 'actual')
    # ### end Alembic commands ###
