"""增加cases表中的预期结果和实际结果字段

Revision ID: dc2cc655245f
Revises: 8f1c525a7d90
Create Date: 2022-09-30 15:14:31.342377

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dc2cc655245f'
down_revision = '8f1c525a7d90'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('actual', sa.TEXT(), nullable=True, comment='断言-实际结果'))
    op.add_column('cases', sa.Column('expect', sa.TEXT(), nullable=True, comment='断言-预期结果'))
    op.add_column('cases', sa.Column('comparison', sa.TEXT(), nullable=True, comment='断言符号'))
    op.alter_column('cases', 'datas',
               existing_type=mysql.TEXT(collation='utf8_bin'),
               comment='测试数据，请求方式、请求体、请求头',
               existing_comment='测试数据，请求方式、请求体、请求头、预期和实际结果',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cases', 'datas',
               existing_type=mysql.TEXT(collation='utf8_bin'),
               comment='测试数据，请求方式、请求体、请求头、预期和实际结果',
               existing_comment='测试数据，请求方式、请求体、请求头',
               existing_nullable=False)
    op.drop_column('cases', 'comparison')
    op.drop_column('cases', 'expect')
    op.drop_column('cases', 'actual')
    # ### end Alembic commands ###
