"""修改表结构

Revision ID: ff76f737120e
Revises: 53a28a4b0ab8
Create Date: 2022-09-26 15:28:28.562409

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ff76f737120e'
down_revision = '53a28a4b0ab8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.Column('headers', sa.String(length=200), nullable=False),
    sa.Column('body_type', sa.String(length=10), nullable=False),
    sa.Column('params', sa.String(length=50), nullable=False),
    sa.Column('body', sa.String(length=200), nullable=False),
    sa.Column('cookies', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_time', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('body'),
    sa.UniqueConstraint('body_type'),
    sa.UniqueConstraint('cookies'),
    sa.UniqueConstraint('headers'),
    sa.UniqueConstraint('method'),
    sa.UniqueConstraint('params')
    )
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', mysql.VARCHAR(collation='utf8_bin', length=20), nullable=False))
    op.drop_table('datas')
    # ### end Alembic commands ###
