default_context:
  project_name: 'back_end_develop'
  project_slug: 'back_end_develop'
  domain_main: 'back_end_develop.com'
  domain_staging: 'stag.back_end_develop.com'
  docker_swarm_stack_name_main: 'back_end_develop-com'
  docker_swarm_stack_name_staging: 'stag-back_end_develop-com'
  secret_key: 'HS256'
  first_superuser: 'debugfeng'
  first_superuser_password: '123456'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.back_end_develop.com", "https://stag.back_end_develop.com", "https://back_end_develop.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@back_end_develop.com'
  postgres_password: '123456'
  pgadmin_default_user: 'root'
  pgadmin_default_user_password: '123456'
  traefik_constraint_tag: 'back_end_develop.com'
  traefik_constraint_tag_staging: 'stag.back_end_develop.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:123456'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
